site_name: Maxar-OGC Docs


nav:
    - Home: 'index.md'
    - Quickstart: 'quickstart.md'
    - Search: 'image_search.md'
    - Download:
        - 'download_image.md'
        - 'download_browse_image.md'
        - 'download_image_featureid.md'
        - 'download_image_pixel_count.md'
        - 'download_tiles.md'
        - 'get_full_res_image.md'
    - 'Misc':
        - 'band_manipulation.md'
        - 'create_mosaic.md'
        - 'cli_commands.md'
    - 'Release Notes':
        - 'release_notes.md'

docs_dir: './ogc-sdk/docs'
site_dir: './ogc-sdk/site'
theme:
  name: material
  logo: maxar_gold_logo_rgb_250.png
  favicon: favicon.ico
  custom_dir: './ogc-sdk/docs/stylesheets'
extra_css: 
    - stylesheets/extra.css

