site_name: Maxar-OGC Docs


nav:
    - Home: 'index.md'
    - 'image_search.md'
    - Download:
        - 'download_image.md'
        - 'download_browse_image.md'
        - 'download_image_featureid.md'
        - 'download_image_pixel_count.md'
        - 'download_tiles.md'
        - 'get_full_res_image.md'
    - 'band_manipulation.md'
