# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml
build:
  tools:
    python: "3.8"


mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: ./ogc-sdk/requirements.txt

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
