site_name: Maxar-OGC Docs
repo_url: https://github.com/DigitalGlobe/CloudServices
edit_uri: blob/master/docs

nav:
    - Home: 'index.md'
    - 'image_search.md'
    - 'metadata.md'
    - Download:
        - 'download_image.md'
        - 'download_browse_image.md'
        - 'download_image_featureid.md'
        - 'download_image_pixel_count.md'
        - 'download_tiles.md'
    - 'discover_browse.md'
    - 'band_manipulation.md'
